### ISSUE TITLE
JSON Format

### ISSUE THREAD

**Issue by bgott** [ajgrover/model-visualizer#3]
Need to figure out what is the optimal format of model data to pass into the visualizer such that we aren't wasting time re-parsing anything from a string format, or using an inefficient sort/search in order to display each node with its [association] edges.

**Comment by alex-grover** [comment]
JSON would be good for this as you can just use `JSON.parse` from the javascript which will automatically turn it into a js object. 

To do this from the Ruby end, [it looks like we can do](http://ruby-doc.org/stdlib-2.0/libdoc/json/rdoc/JSON.html)

``` ruby
require 'json'
JSON.generate(model)
```

if we want to convert an object or array. Not sure if this will work with our `Model` class - we should test. may require defining a `to_json` method ourselves to serialize all the properties.

**Comment by alex-grover** [comment]
In terms of the format, right now we're storing a hash of name->model object which should be sufficient? We changed it from an array and this is definitely better but I'm not sure how you guys are handling the lookups on the JS end.

**Comment by alex-grover** [comment]
Implemented by 6213e5b.
