### ISSUE TITLE
More robust model and schema parsers

### ISSUE THREAD

**Issue by alex-grover** [ajgrover/model-visualizer#4]
Following @Sxl1092 's email - the parser fails if we have lines with the substring `class` that are not actually defining a class. It also fails for schemas with attributes defined because the regex does not match the trailing comma. We need to make the parser more robust to handle all types of files.

This could potentially be done by using the regex to test for class definitions rather than `line.include?` and check that the returned match is not `nil`.

We should get this done by next Tuesday, 5/5.

**Comment by ryanrperez** [comment]
Fixed with commit 11ab2eebe4115a606b638e058b174b21547ed262
